### ISSUE TITLE
Device or resource busy

### ISSUE THREAD

**Issue by pmonks** [peterschwarz/clj-gpio#1]
This probably isn't a valid issue, but I couldn't find anywhere better to ask the question - my apologies if you have a ML or IRC or whatever that I didn't find.

Anyhoo...

I've just started playing with clj-gpio (nice work btw!) and have run into this situation:

```
user=> (require '[gpio.core :refer :all] :reload)
nil
user=> (def port (open-port 17))

CompilerException java.io.IOException: Device or resource busy, compiling:(form-init6644954132703842785.clj:1:11)
```

Any hints as to what I'm doing wrong?

I had previously been playing with a small C program that toggled the LED on GPIO17 via the wiringPi library, but as far as I can see there's no cleanup mechanism in wiringPi (nor, as best I can tell, is such a thing required).

I can run & rerun the C program, regardless of the state of the LED, and it functions fine.  I'm assuming there's some kind of GPIO reset or cleanup that's needed before clj-gpio will function, but I'm at a bit of a loss as to what it might be.  Any tips would be greatly appreciated.

Thanks again for creating & sharing clj-gpio!

**Comment by pmonks** [comment]
After restarting the pi this code is running perfectly, both before and after the C program runs, so I'm happy to chalk this up to some kind of non-reproducible problem.  ;-)

**Comment by peterschwarz** [comment]
WiringPI doesn't do a very good job of cleaning up its resources while running (hence why I wrote this - Pi4J is based on WiringPI, and therefore isn't REPL friendly), but it shouldn't have held onto them after the C program completed.  

If you run into again, reopen this issue, maybe there's a path where it happens.

**Comment by xerp** [comment]
Hello, I have the same issue, i reboot my pi, but does not work.

**Comment by peterschwarz** [comment]
What are you doing to get into the situation?  Could you provide some example code?

**Comment by xerp** [comment]
Sure,
Here
`(require '[gpio.core :refer :all] :reload)`
`;=>nil`
`(def port (open-port 16))`
`;=>CompilerException java.io.IOException: Device or resource busy`

This is on Raspberry Pi 2 model B+
