### ISSUE TITLE
clj-gpio as unprivileged user

### ISSUE THREAD

**Issue by engblom** [peterschwarz/clj-gpio#6]
Recent changes in Raspbian (Jessie based) has added the gpio user group, exposing /sys/class/gpio/\* to all users belonging to the gpio group. Recent changes to Pi4J allows you to manipulate gpio from an unprivileged account. (details at http://www.raspihub.com/go/750649b302ba1643800a0f4391965c5a22127e8194eeab93d33fa877bb42df7e).

It would be nice if also clj-gpio could benefit from this. Some changes are needed.

$ ls -l /sys/class/gpio/
total 0
-rwxrwx--- 1 root gpio 4096 Dec 22 11:38 export
lrwxrwxrwx 1 root gpio    0 Dec 22 11:38 gpio4 -> ../../devices/platform/soc/3f200000.gpio/gpio/gpio4
lrwxrwxrwx 1 root gpio    0 Dec 22 11:17 gpiochip0 -> ../../devices/platform/soc/3f200000.gpio/gpio/gpiochip0
-rwxrwx--- 1 root gpio 4096 Dec 22 11:17 unexport

ls -l /sys/class/gpio/gpio4/
total 0
-rwxrwx--- 1 root gpio 4096 Dec 22 11:38 active_low
lrwxrwxrwx 1 root gpio    0 Dec 22 11:38 device -> ../../../3f200000.gpio
-rwxrwx--- 1 root gpio 4096 Dec 22 11:38 direction
-rwxrwx--- 1 root gpio 4096 Dec 22 11:38 edge
lrwxrwxrwx 1 root gpio    0 Dec 22 11:38 subsystem -> ../../../../../../class/gpio
-rwxrwx--- 1 root gpio 4096 Dec 22 11:38 uevent
-rwxrwx--- 1 root gpio 4096 Dec 22 11:38 value

'id' shows I am in the gpio group.

From a repl:

led.core=> (def port (open-port 4))

CompilerException java.io.FileNotFoundException: /sys/class/gpio/gpio4/value (Permission denied), compiling:(form-init7914451877660249273.clj:1:11)

**Comment by engblom** [comment]
(spit "/sys/class/gpio/export" "4") 
(spit "/sys/class/gpio/gpio4/direction" "out")
(spit "/sys/class/gpio/gpio4/value" "1")

These 3 lines successfully puts the led to shine, even if I am logged in as an unprivileged user, so the permissions are right. Still, when using the library it claims "Permission denied".

**Comment by peterschwarz** [comment]
Looking a little further into this, I've looked

**Comment by peterschwarz** [comment]
I immediately get the following:

```
user=> (spit "/sys/class/gpio/export" "18")

IOException Device or resource busy  java.io.FileOutputStream.writeBytes (FileOutputStream.java:-2)
```

Looking into the how unprivileged access works, it looks like it's reading and writing directly from the memory mapped interface.  WiringPi is using this directly, but clj-gpio doesn't use that under the hood (it isn't releasing resources in a way that keeps things REPL-friendly).  

I'll have to figure out how to use the memory mapped interface.   Perhaps by creating some JNA wrappers for this library: http://www.airspayce.com/mikem/bcm2835/index.html

**Comment by engblom** [comment]
Are you sure the pin 18 is not already exported? I get that message only if it is already exported. You could try:
(spit "/sys/class/gpio/unexport" "18")
(spit "/sys/class/gpio/export" "18")
(spit "/sys/class/gpio/gpio18/direction" "out")
(spit "/sys/class/gpio/gpio18/value" "1")
(spit "/sys/class/gpio/gpio18/value" "1")

That works for me, with unprivileged access. (With fully updated Raspbian Jessie and belonging to the gpio group)

**Comment by engblom** [comment]
Even though I do not fully understand the code, I have a feeling the RandomAccessFile thing breaks it, as I get everything to work with 'spit' and 'slurp'...

**Comment by peterschwarz** [comment]
Deployed this in

`[clj-gpio "0.2.0-SNAPSHOT"]`
