### ISSUE TITLE
open-channel-port throws exception

### ISSUE THREAD

**Issue by engblom** [peterschwarz/clj-gpio#8]
Something is wrong in 0.2.0-snapshot when it comes to channels:

> => (def ch-port (open-channel-port 18))
> 
> <CompilerException java.lang.NullPointerException, compiling:(form-init7677802202126267607.clj:1:14)

**Comment by peterschwarz** [comment]
Right, looks like that RandomAccessFile was necessary for later use...  I'll have to rework that a bit.
